# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MasterImpl.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10MasterImpl.proto\"\x18\n\x06Worker\x12\x0e\n\x06worker\x18\x01 \x01(\t\" \n\nWorkerList\x12\x12\n\nworkerList\x18\x03 \x03(\t\"\r\n\x0b\x45mptyMaster2~\n\tMasterAPI\x12!\n\x08\x61\x64\x64_node\x12\x07.Worker\x1a\x0c.EmptyMaster\x12$\n\x0bremove_node\x12\x07.Worker\x1a\x0c.EmptyMaster\x12(\n\x0bget_workers\x12\x0c.EmptyMaster\x1a\x0b.WorkerListb\x06proto3')



_WORKER = DESCRIPTOR.message_types_by_name['Worker']
_WORKERLIST = DESCRIPTOR.message_types_by_name['WorkerList']
_EMPTYMASTER = DESCRIPTOR.message_types_by_name['EmptyMaster']
Worker = _reflection.GeneratedProtocolMessageType('Worker', (_message.Message,), {
  'DESCRIPTOR' : _WORKER,
  '__module__' : 'MasterImpl_pb2'
  # @@protoc_insertion_point(class_scope:Worker)
  })
_sym_db.RegisterMessage(Worker)

WorkerList = _reflection.GeneratedProtocolMessageType('WorkerList', (_message.Message,), {
  'DESCRIPTOR' : _WORKERLIST,
  '__module__' : 'MasterImpl_pb2'
  # @@protoc_insertion_point(class_scope:WorkerList)
  })
_sym_db.RegisterMessage(WorkerList)

EmptyMaster = _reflection.GeneratedProtocolMessageType('EmptyMaster', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYMASTER,
  '__module__' : 'MasterImpl_pb2'
  # @@protoc_insertion_point(class_scope:EmptyMaster)
  })
_sym_db.RegisterMessage(EmptyMaster)

_MASTERAPI = DESCRIPTOR.services_by_name['MasterAPI']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WORKER._serialized_start=20
  _WORKER._serialized_end=44
  _WORKERLIST._serialized_start=46
  _WORKERLIST._serialized_end=78
  _EMPTYMASTER._serialized_start=80
  _EMPTYMASTER._serialized_end=93
  _MASTERAPI._serialized_start=95
  _MASTERAPI._serialized_end=221
# @@protoc_insertion_point(module_scope)
