# Generated by the gRPC-distributed-dataframe Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import MasterImpl_pb2 as MasterImpl__pb2


class MasterAPIStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.add_node = channel.unary_unary(
                '/MasterAPI/add_node',
                request_serializer=MasterImpl__pb2.Worker.SerializeToString,
                response_deserializer=MasterImpl__pb2.EmptyMaster.FromString,
                )
        self.remove_node = channel.unary_unary(
                '/MasterAPI/remove_node',
                request_serializer=MasterImpl__pb2.Worker.SerializeToString,
                response_deserializer=MasterImpl__pb2.EmptyMaster.FromString,
                )
        self.get_workers = channel.unary_unary(
                '/MasterAPI/get_workers',
                request_serializer=MasterImpl__pb2.EmptyMaster.SerializeToString,
                response_deserializer=MasterImpl__pb2.WorkerList.FromString,
                )


class MasterAPIServicer(object):
    """Missing associated documentation comment in .proto file."""

    def add_node(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def remove_node(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_workers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MasterAPIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'add_node': grpc.unary_unary_rpc_method_handler(
                    servicer.add_node,
                    request_deserializer=MasterImpl__pb2.Worker.FromString,
                    response_serializer=MasterImpl__pb2.EmptyMaster.SerializeToString,
            ),
            'remove_node': grpc.unary_unary_rpc_method_handler(
                    servicer.remove_node,
                    request_deserializer=MasterImpl__pb2.Worker.FromString,
                    response_serializer=MasterImpl__pb2.EmptyMaster.SerializeToString,
            ),
            'get_workers': grpc.unary_unary_rpc_method_handler(
                    servicer.get_workers,
                    request_deserializer=MasterImpl__pb2.EmptyMaster.FromString,
                    response_serializer=MasterImpl__pb2.WorkerList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MasterAPI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MasterAPI(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def add_node(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MasterAPI/add_node',
            MasterImpl__pb2.Worker.SerializeToString,
            MasterImpl__pb2.EmptyMaster.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def remove_node(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MasterAPI/remove_node',
            MasterImpl__pb2.Worker.SerializeToString,
            MasterImpl__pb2.EmptyMaster.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_workers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MasterAPI/get_workers',
            MasterImpl__pb2.EmptyMaster.SerializeToString,
            MasterImpl__pb2.WorkerList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
