# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Worker.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cWorker.proto\"\x12\n\x03Url\x12\x0b\n\x03url\x18\x01 \x01(\t\"\r\n\x0b\x45mptyWorker\"\x14\n\x04\x46unc\x12\x0c\n\x04\x66unc\x18\x01 \x01(\t\"\x1e\n\tDataframe\x12\x11\n\tdataframe\x18\x01 \x01(\x0c\"\x16\n\x05Index\x12\r\n\x05index\x18\x01 \x01(\x0c\"\x10\n\x02\x42y\x12\n\n\x02\x62y\x18\x01 \x01(\t\"\x0e\n\x01N\x12\t\n\x01n\x18\x01 \x01(\x03\"\x18\n\x06Values\x12\x0e\n\x06values\x18\x01 \x01(\x0c\"\x16\n\x05Items\x12\r\n\x05items\x18\x01 \x01(\t\"\x14\n\x04\x41xis\x12\x0c\n\x04\x61xis\x18\x01 \x01(\x03\"\x18\n\x06Series\x12\x0e\n\x06series\x18\x01 \x01(\x0c\x32\x86\x02\n\tWorkerAPI\x12\x1e\n\x08read_csv\x12\x04.Url\x1a\x0c.EmptyWorker\x12\x1a\n\x05\x61pply\x12\x05.Func\x1a\n.Dataframe\x12\x1f\n\x07\x63olumns\x12\x0c.EmptyWorker\x1a\x06.Index\x12\x1a\n\x07groupby\x12\x03.By\x1a\n.Dataframe\x12\x16\n\x04head\x12\x02.N\x1a\n.Dataframe\x12\x1b\n\x04isin\x12\x07.Values\x1a\n.Dataframe\x12\x1d\n\x05items\x12\x0c.EmptyWorker\x1a\x06.Items\x12\x15\n\x03max\x12\x05.Axis\x1a\x07.Series\x12\x15\n\x03min\x12\x05.Axis\x1a\x07.Seriesb\x06proto3')



_URL = DESCRIPTOR.message_types_by_name['Url']
_EMPTYWORKER = DESCRIPTOR.message_types_by_name['EmptyWorker']
_FUNC = DESCRIPTOR.message_types_by_name['Func']
_DATAFRAME = DESCRIPTOR.message_types_by_name['Dataframe']
_INDEX = DESCRIPTOR.message_types_by_name['Index']
_BY = DESCRIPTOR.message_types_by_name['By']
_N = DESCRIPTOR.message_types_by_name['N']
_VALUES = DESCRIPTOR.message_types_by_name['Values']
_ITEMS = DESCRIPTOR.message_types_by_name['Items']
_AXIS = DESCRIPTOR.message_types_by_name['Axis']
_SERIES = DESCRIPTOR.message_types_by_name['Series']
Url = _reflection.GeneratedProtocolMessageType('Url', (_message.Message,), {
  'DESCRIPTOR' : _URL,
  '__module__' : 'Worker_pb2'
  # @@protoc_insertion_point(class_scope:Url)
  })
_sym_db.RegisterMessage(Url)

EmptyWorker = _reflection.GeneratedProtocolMessageType('EmptyWorker', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYWORKER,
  '__module__' : 'Worker_pb2'
  # @@protoc_insertion_point(class_scope:EmptyWorker)
  })
_sym_db.RegisterMessage(EmptyWorker)

Func = _reflection.GeneratedProtocolMessageType('Func', (_message.Message,), {
  'DESCRIPTOR' : _FUNC,
  '__module__' : 'Worker_pb2'
  # @@protoc_insertion_point(class_scope:Func)
  })
_sym_db.RegisterMessage(Func)

Dataframe = _reflection.GeneratedProtocolMessageType('Dataframe', (_message.Message,), {
  'DESCRIPTOR' : _DATAFRAME,
  '__module__' : 'Worker_pb2'
  # @@protoc_insertion_point(class_scope:Dataframe)
  })
_sym_db.RegisterMessage(Dataframe)

Index = _reflection.GeneratedProtocolMessageType('Index', (_message.Message,), {
  'DESCRIPTOR' : _INDEX,
  '__module__' : 'Worker_pb2'
  # @@protoc_insertion_point(class_scope:Index)
  })
_sym_db.RegisterMessage(Index)

By = _reflection.GeneratedProtocolMessageType('By', (_message.Message,), {
  'DESCRIPTOR' : _BY,
  '__module__' : 'Worker_pb2'
  # @@protoc_insertion_point(class_scope:By)
  })
_sym_db.RegisterMessage(By)

N = _reflection.GeneratedProtocolMessageType('N', (_message.Message,), {
  'DESCRIPTOR' : _N,
  '__module__' : 'Worker_pb2'
  # @@protoc_insertion_point(class_scope:N)
  })
_sym_db.RegisterMessage(N)

Values = _reflection.GeneratedProtocolMessageType('Values', (_message.Message,), {
  'DESCRIPTOR' : _VALUES,
  '__module__' : 'Worker_pb2'
  # @@protoc_insertion_point(class_scope:Values)
  })
_sym_db.RegisterMessage(Values)

Items = _reflection.GeneratedProtocolMessageType('Items', (_message.Message,), {
  'DESCRIPTOR' : _ITEMS,
  '__module__' : 'Worker_pb2'
  # @@protoc_insertion_point(class_scope:Items)
  })
_sym_db.RegisterMessage(Items)

Axis = _reflection.GeneratedProtocolMessageType('Axis', (_message.Message,), {
  'DESCRIPTOR' : _AXIS,
  '__module__' : 'Worker_pb2'
  # @@protoc_insertion_point(class_scope:Axis)
  })
_sym_db.RegisterMessage(Axis)

Series = _reflection.GeneratedProtocolMessageType('Series', (_message.Message,), {
  'DESCRIPTOR' : _SERIES,
  '__module__' : 'Worker_pb2'
  # @@protoc_insertion_point(class_scope:Series)
  })
_sym_db.RegisterMessage(Series)

_WORKERAPI = DESCRIPTOR.services_by_name['WorkerAPI']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _URL._serialized_start=16
  _URL._serialized_end=34
  _EMPTYWORKER._serialized_start=36
  _EMPTYWORKER._serialized_end=49
  _FUNC._serialized_start=51
  _FUNC._serialized_end=71
  _DATAFRAME._serialized_start=73
  _DATAFRAME._serialized_end=103
  _INDEX._serialized_start=105
  _INDEX._serialized_end=127
  _BY._serialized_start=129
  _BY._serialized_end=145
  _N._serialized_start=147
  _N._serialized_end=161
  _VALUES._serialized_start=163
  _VALUES._serialized_end=187
  _ITEMS._serialized_start=189
  _ITEMS._serialized_end=211
  _AXIS._serialized_start=213
  _AXIS._serialized_end=233
  _SERIES._serialized_start=235
  _SERIES._serialized_end=259
  _WORKERAPI._serialized_start=262
  _WORKERAPI._serialized_end=524
# @@protoc_insertion_point(module_scope)
